src/apis/SubtaskAPI.ts, src/storage/Database.ts, test/unit/apis/SubtaskApiSpec.ts, test/unit/apis/TaskApiSpec.ts, test/unit/apis/TasklistApiSpec.ts
=> ISSUE(storage/database): 在 storeOne 的时候，如果存在缓存则更新它

src/apis/ProjectAPI.ts, src/apis/utils.ts, src/app.ts, test/unit/app.ts, test/unit/utils/observable.ts
loading$ 在 Observable 被 create 的时候同时被创建，初始值为 true，在 observer next 或 error 的时候产生一次false 值
=> TPLN-223: 为 Observable 增加 loading$ 属性，这个属性是一个 Observable<boolean>

src/sockets/EventMaps.ts, test/unit/socket/task.ts
=> TPLN-229: 处理 socket change 事件时，change 的对象不存在的情况

mock/backend.ts, mock/mock.ts, mock/response.ts, mock/utils.ts, src/apis/utils.ts, src/models/BaseCollection.ts, src/storage/Database.ts, src/utils/index.ts, test/unit/apis/CommonApiSpec.ts, test/unit/apis/EntrycategoryApiSpec.ts, test/unit/apis/SubtaskApiSpec.ts, test/unit/apis/TaskApiSpec.ts, test/unit/app.ts
=> TPLN-246: 让 mock 库支持为一个 URI 定义多个返回值

mock/index.ts
=> chore: 更新了 mock 模块的依赖

README.md
=> docs: 更新 README

README.md
=> 修正 README.md 中出错的 @component

package.json, src/app.ts, src/fetchs/SubtaskFetch.ts, tsconfig.json, tslint.json
=> Upgrade ts

src/utils/Fetch.ts, test/unit/apis/SubtaskApiSpec.ts, test/unit/apis/TaskApiSpec.ts, test/unit/utils/fetch.ts
=> fix(utils/Fetch): correct AjaxReponse to AjaxError in error handler

package.json, src/SDK.ts, test/apis/user.spec.ts
- 使用正式版本的 ReactiveDB
- 使用 Database#upsert 代替 insert 和 update 方法
=> Use Database#upsert instead of insert and update

src/apis/post/getMyProjects.ts, src/apis/post/getProjects.ts, tools/tasks/bundle.sdk.ts
post 列表应该按 pin 和 created, lastCommentedAt 排序
=> fix(apis/post): posts orderBy

src/apis/post/create.ts, src/apis/post/update.ts, src/schemas/Post.ts
=> fix(schemas/post): 纠正 postMode 类型为 'md' | 'html'

src/apis/event/EventGenerator.ts, test/apis/EventGenerator.spec.ts, test/fixtures/events.fixture.ts
=> fix(EventGenerator): 确保 next 方法正确返回 done 字段

src/Net/Net.ts
=> fix(net): persis should in time order

src/Net/Http.ts, src/SDKFetch.ts, src/utils/helper.ts, test/SDKFetch.spec.ts, test/net/http.ts, test/utils/utils.ts
- 对空`query`对象添加判断
- 忽略`query`对象中的`_`key 并`console.warn`
- 修正`net/http`中的类型报错
=> fix(SDKFetch.get): empty query object should work correctly

package.json
=> chore(package): update @types/node to version 8.0.10

src/utils/Dirty.ts
`markmute`推过来的`socket`带一个`updated`时间戳，会更新`messageList`的顺序.. 需要在`Dirty`里正确处理这个`socket`
=> fix(socket): handle markmute socket

src/apis/post/getByTagId.ts, src/apis/post/getMyProjects.ts, src/apis/post/getProjects.ts, src/utils/helper.ts, src/utils/internalTypes.ts, test/utils/utils.ts
...并整理用于 RDB 查询的 query 与用于网络请求的 query 的类型区分。
=> refactor(apis): 为使用分页功能的 apis 提供准确的分页相关类型信息

package.json, src/schemas/Activity.ts, src/sockets/SocketClient.ts, yarn.lock
- bump TypeScript version to 2.4.2
- bump deps version
- fix lints
=> feat(typescript): bump typescript version

src/schemas/Message.ts, yarn.lock
This reverts commit 1fee34fe1e1b34e5ae21ce4acb48fd3623f70fb1, reversing
changes made to 154169bac5d4899be4ae5e132cb2067ac943fafb.
=> Revert "Merge pull request #321 from teambition/fix/message"

src/schemas/Task.ts
跟吴老师（ @isayme ）确认过了，`task. recurrence` 取值应该是 `string[] | null`
=> fix(TaskSchema): 更正 `recurrence` 类型

src/apis/room/request.ts, src/teambition.ts
用到 `MemberId` 的目前应该只有 `MemberSchema._memberId` 一个地方……
=> fix(teambition-types): 纠正误用 MemberId 类型的地方

package.json, src/schemas/Activity.ts, src/schemas/Collection.ts, src/schemas/CustomRole.ts, src/schemas/Event.ts, src/schemas/File.ts, src/schemas/HomeActivity.ts, src/schemas/Member.ts, src/schemas/ObjectLink.ts, src/schemas/Post.ts, src/schemas/Project.ts, src/schemas/Subtask.ts, src/schemas/TapChart.ts, src/schemas/TapDashboard.ts, src/schemas/Task.ts
...原 member 数据模型用 userId 作为主键，实践中发现是有巨大限制性的。
=> issue(schema/member): 配合 member 数据模型将 memberId 作为主键的迁移

src/schemas/UserMe.ts, src/teambition.ts, test/fixtures/user.fixture.ts
=> feat(schemas): 为 ExecutorOrCreator 类型添加 isRobot 可选字段

src/schemas/Task.ts
=> issue(TaskSchema): 为 TaskSchema 添加 sprint 字段

src/schemas/SmartGroup.ts, src/schemas/Sprint.ts
Sprint:
- noStoryPointTaskCount: number
SmartGroup:
- type: 'story' | 'sprint' | 'bug'
=> issue(schemas/[Sprint, SmartGroup]): 添加应用字段

mock/socket.ts, src/sockets/TableAlias.ts, test/sockets/mapToTable.spec.ts
=> test(sockets/TableAlias): 为已有的别名匹配条目添加测试

src/Net/Net.ts, test/net/net.ts
...的问题。
在缓存键中添加表名信息。
后续再做基于请求信息的缓存键。
=> fix(cache/requestMap): 在缓存键总包含表名，减少不同请求缓存键相同导致缓存有效性判断错误

src/schemas/ScenarioFieldConfig.ts, src/teambition.ts
re-merge: https://github.com/teambition/teambition-sdk/pull/402
=> feat(schema/ScenarioFieldConfig): 为专业模板添加子任务选项

package.json, src/SDK.ts, src/index.ts, src/sockets/EventMaps.ts, src/sockets/EventParser.ts, src/sockets/Middleware.ts, src/sockets/SocketClient.ts, src/utils/Logger.ts, src/utils/eventToRegexp.ts, src/utils/index.ts, src/utils/internalTypes.ts, src/utils/proxy.ts, test/app.ts, test/sockets/eventParser.spec.ts, test/sockets/interceptor.spec.ts, test/sockets/sockets.spec.ts, yarn.lock
=> feat: 在开发环境下代理 socket 的对象, 以保证拦截器被正确使用

mock/mock.ts, mock/response.ts, src/Net/Http.ts, src/SDKFetch.ts, test/SDKFetch.spec.ts, test/net/http.ts, test/sockets/sockets.spec.ts
=> fix(SDKFetch): 为 query string 做必要的 encoding，以及相关 fix

src/schemas/TaskflowStatus.ts
...提示用户在使用该字段时，自行确认其是否可用。
/cc @WuHuiling  @AmosJin
=> fix(schema): 标 TaskflowStatusSchema 的 taskCount 字段类型为可选

src/schemas/Organization.ts
为兼容自由任务动态附件，在 Organization 上新增 `_defaultCollectionId` 字段
=> feat(schemas/Organization): 添加 `_defaultCollectionId` 字段

package.json
=> chore: 更新 `SDK` 依赖描述

src/schemas/DashboardCard.ts, src/schemas/index.ts
...并为它们起更有唯一性的名称。以便于应用中独立使用它们。
=> issue(Schema): 将 DashboardCardSchema 相关的类型定义 export 出来

src/schemas/Tag.ts
=> fix(schemas/Tag): 向 `TagCategorySchema` 补充遗漏的字段

src/teambition.ts
=> feat(schema): 添加新的 Reminder schema

README.md
=> doc(README): 添加安装说明，提示可能需要 Fetch API polyfill

src/schemas/Event.ts, src/schemas/Task.ts
=> fix(schemas): 为 TaskSchema 和 EventSchema 补充 objectType 字段

src/teambition.ts
新增三个任务类型 Icon: `call`, `visit`, `forum`
=> feat(teambition-types): 为新增的任务类型图标添加对应的类型

src/Net/Net.ts
...long overdue documentation@~@
=> doc(Net): 为 CacheStrategy 以及其枚举值做文档说明

yarn.lock
see: https://github.com/yarnpkg/yarn/pull/5042 and https://github.com/yarnpkg/yarn/issues/816
=> chore(yarn.lock): 补充自 yarn@1.10.1 起默认添加的 integrity 字段

src/schemas/Testhub.ts
...确保查询条件能完整对应到 schema 上，如查询某个企业下的 testhub。
=> fix(schemas): 为 Testhub 补充 _organizationId, creator 字段定义

src/schemas/Task.ts, src/teambition.ts
...更准确反应实际数据，帮助应用代码及时处理空值情况。
...resolves #537 .
=> fix(schemas/task): 为如 _executorId, executor 等字段补充空值定义

src/Net/Net.ts, test/net/net.ts
=> fix(Net): 避免 padding 机制无谓多次推值，且推出的是未完整填补的数据

src/schemas/Message.ts, src/schemas/UserMe.ts
=> doc(schemas): 为几个类型添加注释，并引入 UserMe 同等类型 UserSchema

src/schemas/Post.ts
=> fix(schemas): 为 PostSchema['visible'] 使用更准确的类型定义

src/apis/TaskAPI.ts, src/models/BaseModel.ts, src/storage/Database.ts
https://github.com/teambition/teambition-sdk/commit/1963b0dfc860f39894a7936d37677d881b6a6b6a
=> fix(apis/TaskAPI): 修复了当请求任务数据返回空数组时，由于数据不会被缓存而出现错误问题
