teambition/teambition-sdk

src/schemas/File.ts, src/schemas/Message.ts, src/schemas/Project.ts, src/schemas/Task.ts, src/schemas/schema.ts, src/storage/Database.ts, src/storage/Model.ts, test/unit/apis/MessageApiSpec.ts, test/unit/apis/ProjectApiSpec.ts, test/unit/storage/DatabaseSpec.ts
如果一个对象包含在另一个对象中，且没有显式指定 child，它就无法被正常的 new 为一个schema，所以在 storeOne 之后将它的
checkSchema 方法设置为返回 true
=> ISSUE(storage/database): 修复了一些情况下 checkSchema 总是失败的问题

src/models/BaseCollection.ts, test/unit/storage/BaseCollectionSpec.ts
如果直接缓存 this._saveCollection 的流就会导致除了第一次以外的流不处理数据更新，也会导致重复存储同一个 collection。所以需要对 page = 1 的情况做特殊处理。
=> fix(BaseCollection): 修复 BaseCollection 在处理分页逻辑上的错误

src/apis/FeedbackAPI.ts, src/models/FeedbackModel.ts, test/unit/apis/FeedbackApiSpec.ts
不仅仅需要用 page， projectId 缓存，还需要用 start to 时间戳
=> TPLN-253: (hotfix) 修复 feedback 缓存 namespace 不正确的问题

src/utils/Fetch.ts
fetch 在某些版本的 chrome 下有奇怪的 bug，会导致浏览器进程卡死
=> TPLN-254: 强制使用 xhr polyfill

mock/socket.ts, src/sockets/EventMaps.ts, src/sockets/SocketClient.ts, test/unit/socket/activity.ts, test/unit/socket/event.ts, test/unit/socket/feedback.ts, test/unit/socket/message.ts, test/unit/socket/project.ts, test/unit/socket/task.ts
SocketClient 在处理 snapper-consumer 回调的时候没有 bind this
=> hotfix: 修复 SocketClient 处理 new 事件的逻辑

src/storage/Model.ts, test/unit/apis/LikeApiSpec.ts
=> hotfix(storage/model): 修复了 model update 的逻辑错误

src/SDKFetch.ts, src/apis/event/get.ts, src/apis/my/count.ts, src/apis/my/recent.ts, src/apis/post/create.ts, src/apis/post/delete.ts, src/apis/post/get.ts, src/apis/post/getByTagId.ts, src/apis/post/getProjects.ts, src/apis/task/get.ts, src/apis/user/addEmail.ts, src/apis/user/update.ts, src/utils/Fetch.ts, test/mock/MockFetch.ts, test/utils/fetch.ts, test/utils/httpErrorSpec.ts
我理解的大方向是，希望将要成为 URL 组成部分的值左右两边不带斜杠，而将添加斜杠的活儿交给最终生成并使用完整 URL 的部件。
具体到这个 PR，一致化取消 path 字段前面所带的斜杠，修复之前因为有的 path 不加斜杠（如：posts），而有些加斜杠（如：projects），所带来的 bug。并在测试中添加检查。
=> TPLN-440: 一致取消将被用于 URL path 字段的值前面的斜杠（“/”）

src/apis/post/getByTagId.ts, src/apis/post/getMyProjects.ts, src/apis/post/getProjects.ts, src/utils/helper.ts, test/apis/post.spec.ts, test/fixtures/posts.fixture.ts, test/utils/utils.ts
...不破坏现有测试。TODO: 添加相应测试。
DEV-2969: 添加测试
DEV-2969: 让 API 用户传入整个 orderBy 数组
...保持面对业务变动的灵活度。
=> DEV-2969: 配合分享墙重构，为 posts 的相关接口添加 orderBy 输入

src/sockets/EventMaps.ts, test/app.ts, test/sockets/index.ts, test/sockets/sockets.spec.ts
先前使用 rdb 的 Database.prototype.get 方法来检查，不能同步地（synchronously）得知找不到表的问题，于是 try...catch 的结构无效。
=> fix(EventMaps): 不为找不到的表抛异常

package.json, src/Net/Net.ts, src/Net/index.ts, src/SDK.ts, src/index.ts, src/sockets/EventMaps.ts, src/sockets/SocketClient.ts, test/app.ts, test/async-rdb/async-rdb.spec.ts, test/async-rdb/index.ts, test/index.ts
- 从`SDK.ts`中把请求处理剥离出来(`src/Net/`)
- `ReactiveDB`异步加载对请求的处理主要在三个部分
1. `getPost`这样的`http`请求
2. `toggleLike`这样的直接对`ReactiveDB`操作的请求
3. `websocket`推送的操作(创建，更改，删除...)
- 添加测试`test/async-rdb`
- 实现细节上，主要是当`ReactiveDB`没进来的时候对三种请求的操作及其参数放进三个`queue`里，进来了以后按顺序把`queue`里的操作`patch`进`ReactiveDB`。为了在`ReactiveDB`没进来的时候依然能正常拿到数据，把`request`流包进假的`selector`(`proxySelector`)中构建`QueryToken`，等`ReactiveDB`进来了以后`switchMap`到真的`QueryToken`。
=> feat(async-load-rdb): 支持异步加载reactivedb

src/sockets/EventParser.ts, src/utils/Dirty.ts, test/sockets/eventParser.spec.ts, test/sockets/index.ts
=> fix(eventParser): 兼容 event string 不带前置冒号的情况

src/schemas/Application.ts, src/schemas/Collection.ts, src/schemas/CustomRole.ts, src/schemas/DefaultRole.ts, src/schemas/Event.ts, src/schemas/File.ts, src/schemas/Like.ts, src/schemas/Member.ts, src/schemas/ObjectLink.ts, src/schemas/Organization.ts, src/schemas/Post.ts, src/schemas/Preference.ts, src/schemas/Project.ts, src/schemas/Stage.ts, src/schemas/Subtask.ts, src/schemas/Task.ts, src/schemas/Tasklist.ts, src/schemas/UserMe.ts, src/sockets/EventMaps.ts
- 将`sdk`中依赖的`reactivedb`部分改成部分导入，以支持`reactivedb`的分包异步加载
=> feat(code-splitting): partial import reactivedb

src/Net/Net.ts, test/net/net.ts
Otherwise, resubscribe the `QueryToken` will repeat the padding request
=> fix(Net): padding request should upsert response into `Database`

src/apis/event/EventGenerator.ts, test/apis/EventGenerator.spec.ts, test/apis/my.spec.ts, test/fixtures/events.fixture.ts, test/fixtures/my.fixture.ts, test/net/async-rdb.spec.ts
之前的 next 方法第一次拿 startDate 没有经过 rrule.after 检查，导致及时第一个 startDate 不在 rruleset 所可能的实例中，也会被 next 生成出来。
=> fix(EventGenerator): next 能处理初始startDate被exclude的重复日程

src/apis/event/EventGenerator.ts, test/apis/EventGenerator.spec.ts
原来的 next() 函数在生成最后一个合法 value 时同时返回 done: true，这与 [iterator protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) 不同，并且会导致用户程序需要使用 do...while 循环体，容易出错。修改后的 next() 在生成最后一个合法 value 之后，下一次调用时才返回 done: true。
...并更精确地定义 takeFrom 和 takeUntil 的边界行为：
- takeFrom 在开始处会包含 startDate 不在区间内的未结束日程，在终结处会包含 endDate 不在区间内但已经开始的日程，并且可以额外添加一个针对 endDate 的截止时间作为第三个参数；
- takeUntil 如 takeFrom.bind(this, new Date(this.event.startDate))。
...并添加 after 接口
上面三个接口皆能同时在普通日程和重复日程上工作。
=> refactor(EventGenerator): 令 next() 遵从 iterator protocol

src/Net/Http.ts
=> fix(http): http map method type error

mock/mock.ts, src/Net/Http.ts, src/SDKFetch.ts, src/fetchs/SocketFetch.ts, src/index.ts, test/SDKFetch.spec.ts, test/index.ts, test/mock/MockFetch.ts, test/net/http.ts, test/net/net.ts, test/utils/httpErrorSpec.ts
...以支持一个请求的“返回值”要在多个地方做多种转换的场景。
并根据使用中遇到的可用性问题，调整 Net/Http 和 SDKFetch 的接口：
- 将 Net/Http 视为主要面向 SDK 内部使用的接口，而把 SDKFetch 的接口设
计为外部用户习惯的形态；
- Net/Http 中的 get/post/put/delete 方法不再接受 url 或 path 作为参数，
因为完整的 url 已经在其构造函数中定义；
- SDKFetch 中的 get/post/put/delete 方法接受 path 参数，以及其他参数，
每一个调用都会 new 一个对应的 Http 对象，并传入完整 url，及相关参数；
- SDKFetch 中允许 setHeaders, setToken, setOptions。
=> refactor(Net/Http, SDKFetch): 为 Net/Http 添加 clone 方法

src/apis/event/EventGenerator.ts, test/apis/EventGenerator.spec.ts
...重复日程的 startDate 可能已经被 exclude 掉了，但 slice 依然使用这个
startDate 作为第一个日程实例的开始时间，这是错误的。
之前针对这个问题，在 next() 方法里已经修复过一次。此次在 slice 里复发，
说明这个问题需要有更好的解决办法。再想。
=> fix(EventGenerator): 修复内部方法 slice 中一个 edge case

src/apis/event/EventGenerator.ts, test/apis/EventGenerator.spec.ts, test/fixtures/events.fixture.ts
...同时把相关边界条件，以及之前部分 bugfixes 遇到的边界条件，处理的逻辑放在私有方法 getTimeframeFromRecurrence 里，不再重复出现在 next 以及 take...（其下调用的同一个私有方法 slice）。
=> fix(EventGenerator): 令 next 以及 take... 方法正确处理 空 重复日程

.travis.yml, src/apis/ProjectAPI.ts, test/unit/apis/ProjectApiSpec.ts
- 新建一个项目后，会添加自己为members。后端在创建数据时，会默认将creator添加为involvemember，因此添加用户时候后端认为没有数据变化，所以将会返回一个空数组，所以无法再缓存中lookup到自己。
所以这里的策略是在创建project后，手动fetch一次project member
=> fix(create-project): 创建一个全新的项目之后，手动fetch一次members

README.md, package.json, tools/tasks/publish.ts
- 修复`publish_all`中`ts-node publish.ts`的`node`脚本创建目录错误
- 添加`npm scripts (npm run publish_sdk)` 简化发布流程
=> fix(publish): compile err in publish_all and add publish_sdk

src/Net/Http.ts
...从而令 ts 能正确推导出传入 mapfn 的输入类型（`Observable<T>`），并通
过传入 mapfn 的输出类型（`Observable<U>`）推导出 map 所得 Http 对象的类
型（`Http<U>`）。
注：修正前 map 方法的类型定义是错的，里面涉及的类型参数名 U 分属两个类
型参数，并不相同，具有迷惑性。
=> fix(Http): 修正 Http 对象下 map 方法的类型定义

src/Net/Http.ts, src/Net/Net.ts, src/SDKFetch.ts, src/apis/event/get.ts, src/apis/file/get.ts, src/apis/like/get.ts, src/apis/like/toggleLike.ts, src/apis/my/count.ts, src/apis/my/recent.ts, src/apis/organization/projects.ts, src/apis/post/create.ts, src/apis/post/delete.ts, src/apis/post/get.ts, src/apis/post/getByTagId.ts, src/apis/post/getProjects.ts, src/apis/post/update.ts, src/apis/project/personal.ts, src/apis/search/members.ts, src/apis/task/get.ts, src/apis/user/addEmail.ts, src/apis/user/update.ts, src/fetchs/SocketFetch.ts, src/sockets/SocketClient.ts, test/SDKFetch.spec.ts, test/apis/organization.spec.ts, test/apis/project.spec.ts, test/apis/search.spec.ts, test/net/http.ts, test/net/net.ts
...而不是 Http 对象。
为 SDKFetch HTTP 方法接口提供 options 参数，如下：
```typescript
export interface SDKFetchOptions {
includeHeaders?: boolean, // 结果是否包含 response headers
wrapped?: boolean         // 返回 Http 对象还是返回 Observable
}
```
在 SDKFetch 的 HTTP 方法接口上，做了如下修改：
> 每个方法在原有参数列表之后添加一个 options 参数，默认值为 `{}`。即：默认不需要 response headers，且直接返回 Observable。
>
> 当且仅当传入 options 参数里有 `wrapped` 字段的值为真，返回 Http 对象，其余情况均返回 Observable。
在 Http 的接口上，保留原有设计，调用 `get/put/post/delete` 之后需要通过再调用 `send` 获得 Observable<_response_>。仅做的修改如下：
> 在 Http 构造函数的原参数列表上添加了一个 `includeHeaders` 参数，默认值为 `false`。即：默认不需要 response headers。
在使用到接口的地方，有这样几个改变（或者说回溯到引入 Http 之前的使用方法）：
> 直接调用 SDKFetch 对象上的 `get/put/post/delete` 方法时，不再需要调用 `send()`。
>
> 调用 SDKFetch 对象上的各种 fetch api 接口时，也不再需要调用 `send()`。
>
> 在构造 `Net.prototype.lift` 上的 `request` 字段参数时，传入 …
=> 令 SDKFetch 上的 get/put/post/delete 方法默认返回 Observable

mock/socket.ts, src/sockets/EventMaps.ts, test/sockets/sockets.spec.ts
...修改从 destroy/remove 分别获取要删除的条目 id 的方法。即：
{ e: ":destroy:{modelType}/{modelId}", d: "" }
从 e 字段获取 modelId 作为要删除的条目 id；
{ e: ":remove:{collectionType}/{collectionId}", d: "{modelId}" }
从 d 字段获取 modelId 作为要删除的条目 id；
{ e: ":remove:{collectionType}", d: "{modelId}" }
不论 e 字段是否带有 id 后缀，使用 d 字段作为要删除的条目 id。
=> fix(sockets/EventMaps): 纠正从 destroy/remove 消息到数据库操作的映射

src/schemas/Task.ts
...并使用 Pick<_source_schema_, 'key1' | 'key2' | ...> 来强化 schema
类型之间的关联。
=> fix(TaskSchema): tags 字段应该是数组，而不是单个 tag 对象的类型

src/Net/Http.ts, src/SDKFetch.ts, test/SDKFetch.spec.ts, test/net/http.ts
接口改变：
- ~~SDKFetch 请求方法（get/post/put/delete）的最后一个 options 参数 `wrapped` 字段改名为 `_wrapped`，`includeHeaders` 改名为 `_includeHeaders`。~~
- 该 options 参数添加了对字段 `apiHost`, `token`, 和 `headers` 的支持；并允许用户提供额外的字段。这些 options 将只作用于当前调用方法的请求，不影响 SDKFetch 对象所管理的状态。用户额外添加的字段会被作为真实请求被发出时（Observable.ajax 或 fetch）的 options 参数的对应字段；
- 这里 `headers` 字段接收对象类型，其中有一个可选字段为 `merge`。当用户传入 `headers` 字段对应的对象中，包含 truthy 的 `merge` 值，用户提供的 `headers` 其他字段会以类似于 Object.assign 的形式「添加」到当前 SDKFetch 对象的内部 headers 上；默认情况下，如果 options 参数中 `headers` 的值为 truthy，就会用其「替换」当前 SDKFetch 对象的内部 headers 作为当前请求要使用的 request headers。 
...to resolve #337 .
=>  fix(SDKFetch, Http): 修复原接口不支持用户为单个请求定制配置的问题

tools/tasks/bundle.ts
...包括：
- rollup options.entry 改为 options.input 了
- bundle.generate options.moduleName 改为 options.name 了
- bundle.generate 返回 Promise<{ code, map }> 而不是 { code, map }
=> fix(tools/tasks/bundle): 兼容 rollup 的更新

src/apis/event/EventGenerator.ts, src/apis/event/index.ts, src/apis/event/utils.ts, src/index.ts, test/apis/event/EventGenerator.spec.ts, test/apis/event/event.spec.ts, test/apis/event/index.ts, test/apis/event/utils.spec.ts, test/apis/index.ts, test/utils.ts
...包括：
- isRecurrent: 判断一个日程对象是否为重复日程
- isAllDay: 判断一个日程是否为全天日程
- originEventId: 重复日程的使用时，根据重复规则，常被生成多个日程实例，
而每个这样的日程实例会带区别于原重复日程的 _id，通过该函数从生成的
_id 获取原 _id
=> feat(apis/event): 添加日程相关常用的工具函数，及测试

src/apis/event/utils.ts
...new Date(year, month, day) 中 month 是从零开始计数的。其实不影响程
序逻辑正确性，但为了避免产生误会，使用 new Date(1970, 0, 1) 更准确地表
达。
=> fix(apis/event/utils): 修正 epochTime 定义上对 Date 构造函数的错误使用

src/schemas/ObjectLink.ts
新增的 parent & linked 同 data 参数，存储的是 `关联的父对象` 和 `关联对象`
由于在关联与被关联中同一个对象的 _id 相同，导致前端在 ObjectLinkModel 中为了同步额外去 subscribeTo 从缓存中监听关联内容的变更会出问题。所以通过 parent & linked 来区分他们的关联联系。
ps: 其中 data 仍然保留为了移动端兼容，并且 linked 的内容和 data 一样
=> feat(schemas/Objectlink): 添加 parent, linked 字段以区分关联/被关联

src/sockets/EventMaps.ts
添加 socket 别名，避免 CustomFieldLink socket 推送消息没正确接收问题
=> fix(sockets/tableAlias): CustomfieldLink to CustomFieldLink

package.json, src/Net/Net.ts, src/SDKFetch.ts, tools/tasks/test.ts, yarn.lock
...并根据类型报错修改相关代码。
另：调长测试 watch 模式里的 debounceTime 到 500ms，降低 tsc 新 watch
mode 导致的“重新编译已完成”的误判概率，避免 runTman 在重新编译尚未完成，
而文件更新正在持续输出的情况下，被多次调用，导致某些测试失败。
=> chore(dependency): 升级 typescript 到 2.6

src/SDK.ts, src/sockets/EventMaps.ts, src/sockets/MapToTable.ts, src/sockets/SocketClient.ts, src/sockets/TableAlias.ts, src/utils/internalTypes.ts, test/sockets/index.ts, test/sockets/mapToTable.spec.ts, test/sockets/sockets.spec.ts, test/sockets/tableAlias.spec.ts, test/utils.ts
...同时，剥离从推送消息 type 字段到表名的映射的逻辑至 `TableInfoByMessageType` 类。
TODOs:
添加相关测试：
=> feat(sockets/): 令推送消息 type 字段到表名映射的逻辑 case-insensitive

mock/socket.ts, src/sockets/EventMaps.ts, test/sockets/sockets.spec.ts
批量更新：`{ e: ":change:{modelType}s/{boundToObjectId}", d: "[update1, update2, ...]" }`，其中 `update1, update2` 等为含相应 model 类型主键信息及更新字段信息的对象。
批量删除：`{ e: ":remove:{modelType}s/{boundToObjectId}", d: "[pk1, pk2, ...]" }`，其中 `pk1, pk2` 等对应要删除的 model 的主键。
=> issue(sockets/EventMaps): 支持批量“更新”/“删除”消息

src/apis/post/create.ts, src/schemas/Entry.ts, src/schemas/Event.ts, src/schemas/File.ts, src/schemas/Task.ts, src/teambition.ts
VisibleOption 的枚举值为 `'members' | 'involves'`。
Visibility 定义里 `'all' | 'organization' | 'project'` 为 ProjectSchema 上的 visibility 字段独有，其类型已经写在 `ProjectSchema['visibility']` 上了。而真正用到 Visibility 类型的地方，其值都对应 `'members' | 'involves'`。
所以，修改所有当前使用 Visibility 但其实指 `'members' | 'involves'` 的地方为 VisibleOption，避免与 Visibility 冲突。暂时移除 Visibility，以后需要将 ProjectSchema 上的类型单独提取出来时，再定义 Visibility。
...resolves #431
=> fix(type): 新添 VisibleOption 代替定义错误的 Visibility

src/Net/Http.ts
...原来的实现对 Observable.ajax 的使用中，误把其已经 JSON.parse 过的
AjaxResponse.response 再做了一次 JSON.parse，导致 throw 并总是走 catch
逻辑，间接导致 includeHeaders 选项失效。
Note: 当 responseType 为 json，Observable.ajax 会自动把 JSON.parse 后
的结果给其 response 字段。
=> fix(SDKFetch): 修复其 includeHeaders 选项在实际项目中的有效性

src/Net/Net.ts, src/apis/post/getByTagId.ts, src/apis/post/getMyProjects.ts, src/apis/post/getProjects.ts, test/net/net.ts
为接口用户提供正向指定所需查询字段的办法。解除原先用户只能通过 ApiResult.excludeFields 来排除不要查询的字段（逆向指定）的限制。
ApiResult.query.fields 将比 excludeFields 拥有更高优先级，凡是在 ApiResult.query.fields 里指定的可用查询字段，都会出现在查询结果中。（一般情况下，fields 和 excludeFields 不会同时指定；如果是自动化生成的查询，或者是从查询模板生成的查询，才会发生。另：一个边界情况是， ApiResult.query.fields 如果不包含任何元素，即为 []，与没有指定 ApiResult.query.fields 的行为一致，即认为用户没有正向指定查询字段。）
=> feat(Net): 为 ApiResult.query 添加 fields 字段的支持

src/schemas/CustomField.ts, src/schemas/CustomFieldLink.ts, src/teambition.ts
=> feat(schemas/AdvancedCustomField): 新增高级自定义字段相关类型

src/apis/event/utils.ts, src/schemas/Event.ts, src/schemas/Member.ts, src/schemas/TapDashboard.ts, src/schemas/TapQuestion.ts, src/schemas/UserMe.ts, src/teambition.ts, test/apis/customfieldlink.spec.ts, test/apis/event/EventGenerator.spec.ts, test/apis/event/event.spec.ts, test/apis/file.spec.ts, test/apis/like.spec.ts, test/apis/my.spec.ts, test/apis/organization.spec.ts, test/apis/post.spec.ts, test/apis/project.spec.ts, test/apis/scenariofieldconfig.spec.ts, test/apis/search.spec.ts, test/apis/tag.spec.ts, test/apis/task.spec.ts, test/fixtures/scenariofieldconfigs.fixture.ts, test/net/asyncLoadRDB.ts
各种 id 类型如：UserId, ProjectId, TaskId 等等，它们应该有下列性质：
原来 `interface X extends String { kind?: 'X' }` 的实现，满足了2，但没有满足1、3。
不满足1，导致当需要将 id 数据从带有场景上下文的业务代码传给不关心业务逻辑而只是简单接受 string 的底层组件时，需要通过 `as string` 强转，如果该信息包在一个对象结构里，那这个对象结构要么需要 `as any`，结果丢失所有类型信息，要么底层组件的对应对象结构类型声明就需要添加类型参数（泛型声明），结果增加冗长而意义不大的泛型声明。
而不满足3，会漏掉很多类型检查，因为并不是任何 string 类型的值都可以赋值给特定 id 类型的。
新的写法是：`type X = string & { kind: 'X' }`，它能同时满足1、2、3、4，并在类型报错信息里有比较友好的信息提示。
TODOs:
参考：
- https://codemix.com/opaque-types-in-javascript/
- https://github.com/Microsoft/TypeScript/issues/15807
- https://github.com/Microsoft/TypeScript/issues/4895
- https://github.com/Microsoft/TypeScript/issues/202
- https://github.com/Microsoft/TypeScript/blob/d9b93903c035e48c8da1d731332787f83efc4619/src/compiler/types.ts#L54
=> refactor(typings): 改善和纠正各种 id 类型的性质

src/schemas/Project.ts, src/schemas/Tasklist.ts, src/teambition.ts
...另外，将 sortMethod 对应的类型提出，作 TaskSortMethod，方便单独使用
（用户项目里已经有使用案例）。
TasklistSchema 的 sortMethod 添加了 `''` 类型，与实际后端接口返回匹配。
/cc @coldfannn
=> fix(schemas): 完善 TasklistSchema 的字段，并整理字段在代码中的排序

src/apis/event/EventGenerator.ts
先前的实现，需要从重复规则最早的时间点开始，一个个检查（skip）直到找到
第一个符合区间条件的 timeframe，并将随后的每个 timeframe 生成出来，直
到遇到第一个不符合区间条件的 timeframe 停止。
如果一个重复规则有很多很多出现在区间条件之前的 timeframe，那么开始的
skip 操作就会很多。事实证明，skip 操作里包含的对 RRuleSet after() 的调
用是很昂贵的。
新的实现，去掉了一个个 skip 掉区间条件之前 timeframe 的过程，直接找到
第一个符合区间条件的日程，节省计算昂贵的 RRuleSet after() 调用。
=> perf(EventGenerator): 更高效地找到给定区间在重复规则上的开始点

src/Net/Net.ts
JoinMode 虽然是一个 interface，但由于其本身是一个 enum，TS 在转译的时候会产生运行时代码。 所以这里从 根入口去引用 这个属性会导致整个 reactivedb 的依赖一同进入到项目中，而这在某些场景中是不应该发生的。
=> fix(deps): 避免由 `JoinMode` 引入整个 reactivedb 依赖

src/schemas/Favorite.ts, src/schemas/Subtask.ts
=> fix: 移除不再使用的 `isInbox` 字段

src/schemas/Taskflow.ts
taskflowSchema 增加 taskflowstatuses 字段
=> feat(TaskflowSchema): 增加 `taskflowstatuses` 字段

src/schemas/Project.ts
Ps: 该属性与 isArchived 不可以同时为 true
Note: ProjectSchema 上的 `isArchived` 字段目前语义暂时调整为“移至回收站”，而 `isSuspended` 字段语义为“已归档”。
=> feat(schema): ProjectSchema 新增属性是否已归档 isSuspended

src/Net/Http.ts, src/Net/Pagination.ts, src/SDKFetch.ts
在 `rxjs@6` 环境，需要引入 `observable/throw` 才能正常使用 `Observable.throw` 操作符。
=> fix(rxjs): 补充引入被遗漏的 `observable/throw` 操作符

src/schemas/Task.ts, test/apis/task.spec.ts
@chuan6 我在等待后端答复（任务接口都是有返回 `creator` 字段？）。
=> feat(schemas/Task): 补充已在使用中的 `creator` 字段

mock/mock.ts, src/SDKFetch.ts, test/SDKFetch.spec.ts
纠正在如 `{ involveMembers: [] }` 的 query 对象下，生成的 url 在时间戳片段（`_=nnnnnnnn`）之前带有 `&` 的错误。
问题出现的原因，从代码组织的角度看，是在生成 urlWithTail 时使用的判断条件之一 isEmptyObject(query) 与 buildQuery 内部更准确的空条件判断不吻合，遗漏了空数组的检查。所以，用判断由 buildQuery 生成的 urlWithQuery 是否含有查询部分，来代替原来的 `query && !isEmptyObject(query)`，保证始终使用 buildQuery 的内部判断逻辑，避免以后出现类似问题。
...resolves #535
=> fix(SDKFetch): 避免在 query 唯一键对应值为 [] 时得错误 url

src/SDK.ts, src/utils/internalTypes.ts, test/SDKFetch.spec.ts
这里的实现，粗暴地在后端提供了 `errors` 字段后就放弃 `data` 字段可能存在的有用数据。接下来，应该支持通过解析 `errors` 里 `path` 字段的信息，来支持 `data` 字段数据的部分可用性。https://github.com/teambition/teambition-sdk/issues/552
=> fix(graphql): 补充简单的 errors 字段处理机制

src/Net/Net.ts
当 query token 推出一组 data 时，里面如果存在多个条目需要 padding，那
么就会发出多个请求。当其中有一个请求返回，其结果被 upsert 到 db，就导
致 query token 生成的数据流的新一次推送，造成正在进行的其他 padding 请
求被切掉。而新推出的 data 依然有条目需要 padding，就又要重新开始一系列
padding 请求。依此往复。
exhaustMap 的使用，避免了当前一次推送对应的一系列 padding 请求被切掉。
在 padding 期间的更多推送都被忽略。当 padding 完成，由其更新过的 data
会被推出来，作为最新数据。
另外：令不需要 validate 步骤的数据流直接 pass through，成本低一些。
=> fix(net/validate): 避免 switchMap 中断 padding 请求导致的循环请求

package.json, yarn.lock
Note: 观察到 `yarn watch` 跑得慢了很多，~~可能与 https://github.com/Microsoft/TypeScript/issues/25023 这个 issue 有关~~。`yarn test` 的速度不受影响。以后持续关注 tsc watch mode 相关优化（已修复：see https://github.com/Microsoft/TypeScript/issues/28025 ）。
=> chore(dependency): 升级 typescript 3.1 相关依赖

src/schemas/Task.ts
...这个字段一般只在搜索接口的结果中直接使用，其他场景少有存在的。
Thanks to @AmosJin @aicest !
...resolves #588
=> fix(schemas): 纠正 TaskSchema `project` 字段为可选字段

src/Net/Pagination.ts, src/apis/pagination.ts, src/utils/internalTypes.ts, test/net/pagination.ts
添加 `PageCountState` 类型状态，原来的分页状态定义为 `PageTokenState`（原来的 `State` 指向 `PageTokenState`）。并在相关逻辑内支持 `PageCountState` 需要的特有逻辑。
另外，在状态中补充管理 `limit` 字段，用于方便用户对结果数据做缓存访问。并补充一个衔接 fetch 接口与 缓存接口 的工具函数，`Page.queryInfo`。
TODO: ~~为 wiki 文章补充相关 section~~[另提 PR]
=> feat(pagination): 支持 page + count 类型分页请求

src/Net/Net.ts, test/net/net.ts
用 delayWhen 代替代码里一些使用 concatMap 来做时延但其实不需要结果值的场景。令相关代码语义更明确。
另外，在上边修改涉及到的 padding 机制代码做结构调整，令其更清晰。
Thanks to @DomonJi !
...to resolve #574
=> refactor(Net): 引入 rxjs delayWhen 操作符，令部分逻辑表达更明确

src/schemas/SmartGroup.ts, src/teambition.ts
…ewType 字段
icon字段我设置为了string，后端给的是：['taskToday', 'taskUndone', 'taskDone', 'taskNotAssigned', 'taskMyExecuted']。
@chuan6 你觉得前端这里有必要明确的给出这些枚举吗？
=> feat(schemas/SmartGroup): 支持自定义筛选视图
